name: Deploy to Hestia via FTP

on:
  push:
    branches:
      - main # or whatever branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: hestadmin
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local_path: './*'
          remote_path: '/home/hestadmin/web/andreimendoza.ca/public_html/'
          sftp_only: true
